<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1b67843044d8aa61ca6bac69b526a8f4
{
    public static $files = array (
        '6124b4c8570aa390c21fafd04a26c69f' => __DIR__ . '/imposter-autoload-patcher' . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
        'ec07570ca5a812141189b1fa81503674' => __DIR__ . '/imposter-autoload-patcher' . '/phpunit/phpunit/src/Framework/Assert/Functions.php',
        '7d3b315c4f303f2fc14aca642a738e50' => __DIR__ . '/imposter-autoload-patcher' . '/yoast/phpunit-polyfills/phpunitpolyfills-autoload.php',
        '5848e15fb2a2b986bbe9a447a5beb027' => __DIR__ . '/../bojaghi' . '/inc/continy-helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TypistTech\\Imposter\\' => 20,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Container\\' => 14,
            'PhpParser\\' => 10,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        'D' => 
        array (
            'Doctrine\\Instantiator\\' => 22,
            'DeepCopy\\' => 9,
        ),
        'C' => 
        array (
            'Chwnam\\ThreadsToPosts\\Tests\\' => 28,
            'Chwnam\\ThreadsToPosts\\' => 22,
        ),
        'B' => 
        array (
            'Bojaghi\\Template\\' => 17,
            'Bojaghi\\Helper\\' => 15,
            'Bojaghi\\Fields\\' => 15,
            'Bojaghi\\FieldsRender\\' => 21,
            'Bojaghi\\CustomPosts\\' => 20,
            'Bojaghi\\Cron\\' => 13,
            'Bojaghi\\Contract\\' => 17,
            'Bojaghi\\Continy\\' => 16,
            'Bojaghi\\AdminAjax\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TypistTech\\Imposter\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/typisttech/imposter/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/psr/log/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/psr/container/src',
        ),
        'PhpParser\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/nikic/php-parser/lib/PhpParser',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/monolog/monolog/src/Monolog',
        ),
        'Doctrine\\Instantiator\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/doctrine/instantiator/src/Doctrine/Instantiator',
        ),
        'DeepCopy\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/myclabs/deep-copy/src/DeepCopy',
        ),
        'Chwnam\\ThreadsToPosts\\Tests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'Chwnam\\ThreadsToPosts\\' => 
        array (
            0 => __DIR__ . '/../bojaghi' . '/inc',
        ),
        'Bojaghi\\Template\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/template/src',
        ),
        'Bojaghi\\Helper\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/helper/src',
        ),
        'Bojaghi\\Fields\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/fields/src',
        ),
        'Bojaghi\\FieldsRender\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/fields-render/src',
        ),
        'Bojaghi\\CustomPosts\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/custom-posts/src',
        ),
        'Bojaghi\\Cron\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/cron/src',
        ),
        'Bojaghi\\Contract\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/contract/src',
        ),
        'Bojaghi\\Continy\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/continy/src',
        ),
        'Bojaghi\\AdminAjax\\' => 
        array (
            0 => __DIR__ . '/imposter-autoload-patcher' . '/bojaghi/admin-ajax/src',
        ),
    );

    public static $classMap = array ();

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1b67843044d8aa61ca6bac69b526a8f4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1b67843044d8aa61ca6bac69b526a8f4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1b67843044d8aa61ca6bac69b526a8f4::$classMap;

        }, null, ClassLoader::class);
    }
}
